application: test-momentos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /bootstrap
  static_dir: bootstrap
- url: /guestbook/.*
  script: hello_world.application
- url: /.*
  script: momentos.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
